### ISSUE TITLE
Question : is there acro mode or only angle mode .

### ISSUE THREAD

**Issue by Shally1986** [anish-natekar/PicoW_Copter#1]
Is there acro mode or only angle mode ? Is there plan fo develop acro mode

**Comment by anish-natekar** [comment]
you can disable the auto leveling by changing the values of the variable to false in the flight controller.
This will make it acro mode (3d flight mode).
![image](https://github.com/anish-natekar/PicoW_Copter/assets/72445283/34592253-6cf3-470a-a127-4b7032ec3b2a)
