### ISSUE TITLE
flyback diode

### ISSUE THREAD

**Issue by aashlok** [anish-natekar/PicoW_Copter#4]
In your present circuit design, what function does zener diode serve when attached to gate of mosfet? When mosfet is turned off where does back emf from motor go? I think back emf would fry mosfet in long run. A flyback 5819 schottky diode at drain of mosfet blocking from vcc seems fine for the purpose.

**Comment by anish-natekar** [comment]
Hi aashlok,
the diode i used is this one- https://robu.in/product/1n4148-surface-mount-zener-diode-pack-of-30/
I referred to this video. this is not a zener diode it is a fast switching diode even if it may look like a zener diode - https://www.youtube.com/watch?v=MHtOtM_yWLw
