### ISSUE TITLE
Takeoff not stable

### ISSUE THREAD

**Issue by karimbernardet83** [anish-natekar/PicoW_Copter#8]
Hi

Thank you very much for the tutorial !!!
I made the drone for my children (see photos).
I can't get it to take off in a stable manner. It always goes to one side just by increasing the throttle (I use my phone and udp joystick) and it always ends up turning around. I checked that the propellers are ok and in the right place.
If you have any idea what I could check.
Thank you so much
Karim

![image](https://github.com/anish-natekar/PicoW_Copter/assets/74904741/10053d24-698f-43c5-89af-701a400a744c)
![image](https://github.com/anish-natekar/PicoW_Copter/assets/74904741/a7907683-6b8d-4170-b071-865f74202572)

**Comment by karimbernardet83** [comment]
With a video :-) 

https://drive.google.com/file/d/13v4oZYKWqUHTXwSxi67sw0vTN-VnNnNx/view?usp=drive_link

**Comment by karimbernardet83** [comment]
Got it working

**Comment by anish-natekar** [comment]
Congrats. Sorry I didn't reply back when you needed help. I am not able to manage time these days for building things hope to get back soon and be more active on github.
